/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/eltruforce.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const texture = useTexture('/download.png')
  const data = useGLTF('/eltruforce.glb') as any
  const { nodes, materials, animations } = data

  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          // position={[-0.01, -0.14, 0.1]}
          // rotation={[-0.11, -0.73, 0]}
        >
          <primitive object={nodes.Hips} />
          <skinnedMesh
            castShadow
            name="R_Arm"
            geometry={nodes.R_Arm.geometry}
            material={materials.material_atlas_63611_1}
            skeleton={nodes.R_Arm.skeleton}
          >
            <meshStandardMaterial map={texture} map-flipY={false} skinning />
          </skinnedMesh>
          <group name="Body">
            <skinnedMesh
              castShadow
              name="HandMesh_L_m053"
              geometry={nodes.HandMesh_L_m053.geometry}
              material={materials.material_atlas_63611_1}
              skeleton={nodes.HandMesh_L_m053.skeleton}
              morphTargetDictionary={
                nodes.HandMesh_L_m053.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.HandMesh_L_m053.morphTargetInfluences
              }
            >
              <meshStandardMaterial map={texture} map-flipY={false} skinning />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="HandMesh_L_m053_1"
              geometry={nodes.HandMesh_L_m053_1.geometry}
              material={materials.Face}
              skeleton={nodes.HandMesh_L_m053_1.skeleton}
              morphTargetDictionary={
                nodes.HandMesh_L_m053_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.HandMesh_L_m053_1.morphTargetInfluences
              }
            >
              <meshStandardMaterial map={texture} map-flipY={false} skinning />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eltruforce.glb')
